# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nn_matchC <- function(treat, ord, ratio, replace, discarded, distance_ = NULL, exact_ = NULL, caliper_dist_ = NULL, caliper_covs_ = NULL, calcovs_covs_mat_ = NULL, mah_covs_ = NULL, mahSigma_inv_ = NULL, disl_prog = FALSE) {
    .Call(`_MatchIt_nn_matchC`, treat, ord, ratio, replace, discarded, distance_, exact_, caliper_dist_, caliper_covs_, calcovs_covs_mat_, mah_covs_, mahSigma_inv_, disl_prog)
}

pairdistsubC <- function(x_, t_, s_, num_sub) {
    .Call(`_MatchIt_pairdistsubC`, x_, t_, s_, num_sub)
}

weights_matrix <- function(mm, treat) {
    .Call(`_MatchIt_weights_matrix`, mm, treat)
}

